### ISSUE TITLE
[Fix Speakers] Title text not clear in dark mode

### ISSUE THREAD

**Issue by misshannah** [droidconKE/droidconKeKotlin#138]
**Describe the bug**
The title text in the speaker screen is not visible in dark theme mode

**To Reproduce**

See unreadable sections in screen
1. Change device settings to dark theme before opening the app
2. Go to 'Speakers'
3. See unclear title

**Expected behavior**
Clear title

**Screenshots**
Added screenshot
![Screenshot](https://github.com/droidconKE/droidconKE2023Android/assets/5990196/7ad632b1-16f2-445f-8bb8-552bf7e3d38b)

**Comment by kanake10** [comment]
Hello @misshannah, @chepsi 
Can I make the title `Speakers`  blue?

**Comment by chepsi** [comment]
Fixed: Closing this issue.
