### ISSUE TITLE
[Fix Feed] Text colour not clear in dark mode

### ISSUE THREAD

**Issue by misshannah** [droidconKE/droidconKeKotlin#139]
**Describe the bug**
Some of the text in the feed screen is not visible in dark theme mode

**To Reproduce**
1. Change device settings to dark theme before opening the app 
2. Go to 'Feed'
3. See unreadable sections in screen

**Expected behavior**
Readable text

**Screenshots**
Added screenshot
![Screenshot 2](https://github.com/droidconKE/droidconKE2023Android/assets/5990196/2498946b-7376-4217-9d73-f2322a74f95e)

**Comment by jumapaul** [comment]
@chepsi jumping on this.

**Comment by chepsi** [comment]
This seems to be sorted with a separate PR. closing it now.
