### ISSUE TITLE
Text Color On dark mode

### ISSUE THREAD

**Issue by Noah29m** [droidconKE/droidconKeKotlin#141]
1.Text color doesn't change when selected in bottom Nav
2.Text color not clear on dark mode in sessions screen

**Comment by josphatmwania** [comment]
Hello, @Noah29m Could you please attach the screenshots? 

cc @chepsi, you can assign him this.

**Comment by githukueliud** [comment]
Hello, was this issue resolved?
![droidcon 23](https://github.com/droidconKE/droidconKE2023Android/assets/138256399/60e1c5d4-6c08-480b-946b-bc8082bda9f9)

**Comment by chepsi** [comment]
@githukueliud Not entirely. Would you like to work on it?

**Comment by githukueliud** [comment]
I'll share my thought process then you'll lmk
The color used for this section is ChaiBlue, even though this is the theme color. It spoils the ux for the dark theme. How about ChaiTeal to be used, which is great for both the light and dark mode?

**Comment by githukueliud** [comment]
The about page could also be solved with a similar approach
![droidcon about page](https://github.com/droidconKE/droidconKE2023Android/assets/138256399/c3dbb1e9-ef38-4822-91fe-23196d10a2c1)

**Comment by githukueliud** [comment]
Hey @chepsi assign this to me

**Comment by chepsi** [comment]
This seems to be sorted. closing it now.
