### ISSUE TITLE
Implement Feed Sharing to the Different Platforms

### ISSUE THREAD

**Issue by wangerekaharun** [droidconKE/droidconKeKotlin#172]
Start intents to share feed to:

- Twitter,
- WhatsApp
- Facebook
- Telegram

**Comment by mog-rn** [comment]
@wangerekaharun I can take this.

**Comment by wangerekaharun** [comment]
> @wangerekaharun I can take this.

Assigned you

**Comment by mog-rn** [comment]
@wangerekaharun I am getting client error while on the Feed screen

**Comment by chepsi** [comment]
@mog-rn how are we doing with this?

**Comment by mog-rn** [comment]
Will be sharing my progress by tomorrow @chepsi

**Comment by mog-rn** [comment]
@chepsi can you help me out on this. I will not be able to finish this tasks since I have been having a packed schedule with work.

**Comment by chepsi** [comment]
Marking this as stale
