### ISSUE TITLE
Session Card On homepage not showing image.

### ISSUE THREAD

**Issue by chepsi** [droidconKE/droidconKeKotlin#190]
Ideally, the session card on the home page should show an image. You can compare it with the image when you open Sessions on the bottom navigation and open any session.

Check the screenshot below.
![image](https://github.com/droidconKE/droidconKE2023Android/assets/61404564/fe187fca-aec1-46c7-ad60-cf162152db77)

**Comment by githukueliud** [comment]
Hello, assign this to me
Also I can't seem to be receiving an image for the speakers in the sessions card, was it submitted? Bc I'm also not getting an error.

**Comment by githukueliud** [comment]
![Uploading Screenshot_20231012-044833_DroidconKE2023.jpg…]()

**Comment by githukueliud** [comment]
That's my solution

**Comment by githukueliud** [comment]
![Uploading Screenshot_20231012-044833_DroidconKE2023.jpg…]()

**Comment by chepsi** [comment]
@githukueliud can't seem to see the images uploaded here

**Comment by githukueliud** [comment]
![Uploading Screenshot_20231012-044833_DroidconKE2023.jpg…]()

**Comment by githukueliud** [comment]
![a96a814d-d8dd-4d34-8a7e-1a9a8dc626b7](https://github.com/droidconKE/droidconKeKotlin/assets/138256399/dd21569b-0abd-4ee3-9d49-6a74a9cdb9e2)

**Comment by githukueliud** [comment]
I was unable to load the speaker image for the session card

**Comment by githukueliud** [comment]
Also @chepsi  I was thinking of solving the dark theme issues for for texts like the names of the organizing team etc but I only know how to set it up directly eg color = if (isSystemInDarkTheme) Color.White else {use the color already working for light mode}
I don't know if this will violate the set standards, let me know if that works and I'll work on the issues

**Comment by Terry-Mochire** [comment]
@chepsi  PR #219 closes this issue.
