### ISSUE TITLE
Speaker Image has a teal background

### ISSUE THREAD

**Issue by chepsi** [droidconKE/droidconKeKotlin#192]
Speaker Image, on Home screen and when you view all speakers, has a teal background. This shouldn't be the case.

![Uploading image.png…]()
![Uploading image.png…]()

**Comment by lokified** [comment]
i can work on this issue.

**Comment by chepsi** [comment]
Absolutely @lokified let me know if you need any help. Assigning it to you

**Comment by chepsi** [comment]
Fixed.
