### ISSUE TITLE
Home Screen Clicking on a session doesn't navigate to Session Details

### ISSUE THREAD

**Issue by chepsi** [droidconKE/droidconKeKotlin#193]
When you are on the HomeScreen and Click on a session does not navigate to the session details screen.

**Comment by Raynafs** [comment]
Hey Chepsi. Can I work on this?

**Comment by chepsi** [comment]
Absolutely @Raynafs. I am assigning it to you. Let me know if you need any help.

**Comment by Raynafs** [comment]
Hi Chepsi. I can't seem to find the button that would allow me to login with google so that I can access the sessions.
Please Assist.

**Comment by wangerekaharun** [comment]
You can access the sessions without login in

**Comment by Raynafs** [comment]
How can I do that?

**Comment by wangerekaharun** [comment]
Can you try closing the app and then open again

**Comment by MJJacobs01** [comment]
Good evening @chepsi, 

May I give it a try tomorrow evening?

**Comment by Raynafs** [comment]
Hello, @chepsi 
I run the app and the sessions in the Homescreen navigate to the session details.
Kindly assist.

**Comment by chepsi** [comment]
Hey @Raynafs that's true. This seems to have been fixed in the latest main branch..  Thank you for pointing it out.

**Comment by Raynafs** [comment]
You're welcome. Kindly inform me if there's another issue not assigned
