### ISSUE TITLE
Organising team in AboutScreen 

### ISSUE THREAD

**Issue by chepsi** [droidconKE/droidconKeKotlin#194]
If you navigate to the AboutScreen and scroll to the organizing team you'll notice the items are not spaced properly.

![image](https://github.com/droidconKE/droidconKeKotlin/assets/61404564/374bc045-bc9c-441b-8cfe-77089c5f5c65)

**Comment by jumapaul** [comment]
@chepsi i would like to work on this.

**Comment by chepsi** [comment]
That's great, @jumapaul. assigning it to you. Let me know if you need any help.

**Comment by chepsi** [comment]
Fixed.
