### ISSUE TITLE
Bookmarking a Session hides the rest of the sessions in the timeline

### ISSUE THREAD

**Issue by chepsi** [droidconKE/droidconKeKotlin#195]
If you open the Sessions destination in the bottom navigation and bookmark one session, it hides all the other sessions. This shouldn't be the case.

**Comment by paulodhiambo** [comment]
@chepsi I'll pick this

**Comment by chepsi** [comment]
love the speed @paulodhiambo assigning it to you. let me know if you need any help

**Comment by michaelbukachi** [comment]
This is resolved #266
