### ISSUE TITLE
Dark Mode Link to View All for Speakers and Sessions

### ISSUE THREAD

**Issue by chepsi** [droidconKE/droidconKeKotlin#196]
If you change the device theme to dark mode and open the home screen the link to view all speakers and sessions doesn't match the [designs](https://xd.adobe.com/view/5ec235b6-c3c6-49a9-b783-1f1303deb1a8-0b91/screen/5bc76182-ffcf-49cf-b3fb-afbc0d4818e1/).

![image](https://github.com/droidconKE/droidconKeKotlin/assets/61404564/295571b7-6114-4be2-9d35-ca38ff600982)

**Comment by STARKthegreat** [comment]
I'd like to contribute to this issue. How is the design supposed to appear?

**Comment by chepsi** [comment]
hey @STARKthegreat you can find the design here: https://xd.adobe.com/view/5ec235b6-c3c6-49a9-b783-1f1303deb1a8-0b91/screen/5bc76182-ffcf-49cf-b3fb-afbc0d4818e1/ 
Assigning it to you, let me know if you need any help

**Comment by STARKthegreat** [comment]
I have forked the project.

**Comment by chepsi** [comment]
@STARKthegreat this seems to have been sorted with a separate PR. closing it now.
