### ISSUE TITLE
Dark Mode Feed Screen

### ISSUE THREAD

**Issue by chepsi** [droidconKE/droidconKeKotlin#199]
When you switch to dark mode launch app and open Feed bottom navigation destination, the text is not visible. The dark mode designs can be found [here](https://xd.adobe.com/view/5ec235b6-c3c6-49a9-b783-1f1303deb1a8-0b91/screen/6542ef9c-83d3-4620-be14-dbd5f31c7464/)

![image](https://github.com/droidconKE/droidconKeKotlin/assets/61404564/40eb9290-c807-4696-a372-d542d1c6df21)

**Comment by Terry-Mochire** [comment]
@chepsi Can I work on this one?

**Comment by chepsi** [comment]
Absolutely @Terry-Mochire. Assigning it to you. Let me know if you need any help.

**Comment by chepsi** [comment]
Fixed
