### ISSUE TITLE
Refactor: Use version catalog for existing dependencies.

### ISSUE THREAD

**Issue by chepsi** [droidconKE/droidconKeKotlin#228]
Currently, we have dependencies added in `Project level gradle file` and `Remote data source` that don't match the convention for adding dependencies in the version catalog. We need to refactor them to match the convention. Check the screenshots below;

![image](https://github.com/droidconKE/droidconKeKotlin/assets/61404564/98f4e7d2-f3ef-4f6d-a444-df875b533a4c)
![image](https://github.com/droidconKE/droidconKeKotlin/assets/61404564/cb3baa7c-6f95-4b77-90f5-797056e46a31)
![image](https://github.com/droidconKE/droidconKeKotlin/assets/61404564/2a925c8b-f408-414d-a628-0b2c21aea401)

**Comment by wangerekaharun** [comment]
All yours now @Raynafs

**Comment by Raynafs** [comment]
Hey. I also noticed that one of the data module plugins (Kotlin serialization) didn't match the convention. So I changed it too.

**Comment by kibettheophilus** [comment]
@Raynafs this is done,right?

**Comment by Raynafs** [comment]
Yes it is @kibettheophilus
