### ISSUE TITLE
[Feature] Kiswahili translation

### ISSUE THREAD

**Issue by bkmgit** [droidconKE/droidconKeKotlin#234]
**Is your feature request related to a problem? Please describe.**
Would be great to have the application also available in Kiswahili

**Describe the solution you'd like**
Multilingual application, see for example:
https://github.com/DroidKaigi/conference-app-2023

**Describe alternatives you've considered**
Not considered other alternatives

**Additional context**
It may be helpful to split this into two issues, one to create a translation framework and a further tasks for language translations.

**Comment by chepsi** [comment]
Marking this as stale
