### ISSUE TITLE
[Feature] Add search icon on the speakers page

### ISSUE THREAD

**Issue by princemill** [droidconKE/droidconKeKotlin#236]
**Is your feature request related to a problem? Please describe.**
Having a search icon on the speaker's page would greatly enhance navigation and make it easier to find a specific speaker.

**Comment by ericwafula** [comment]
You can assign me this task

**Comment by chepsi** [comment]
@ericwafula We'll need to get designs first.

**Comment by ericwafula** [comment]
That's okay @chepsi

**Comment by chepsi** [comment]
Marking this as stale
