### ISSUE TITLE
Refactor: The designs tab on the project reamde needs to be refactored

### ISSUE THREAD

**Issue by cliffgor** [droidconKE/droidconKeKotlin#240]
The design tab on the project readme is not set up properly. The markdown whouls be nested as a link instead the link is outside the name.

![image](https://github.com/droidconKE/droidconKeKotlin/assets/17774205/49a1c74f-e697-4c99-8db7-7f06158340c6)

**Comment by cliffgor** [comment]
You can assign me this issue

**Comment by wangerekaharun** [comment]
> You can assign me this issue

Done
