### ISSUE TITLE
Refactor: Clean up libs.versions.toml

### ISSUE THREAD

**Issue by chepsi** [droidconKE/droidconKeKotlin#245]
Conventionally, in `libs.versions.toml` the dependencies should be defined as shown below.
```androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splash" }```
this isn't the case for most of the dependencies. 

We should define the dependency as shown above with the version added in the version's section of the file and update the `ReadMe` file.

**Comment by bagechengzi** [comment]
Can I work on this?

**Comment by kibettheophilus** [comment]
> Can I work on this?

sure @bagechengzi
