### ISSUE TITLE
[Bug Report] Tab state is reset when bookmarking a session

### ISSUE THREAD

**Issue by etonotieno** [droidconKE/droidconKeKotlin#267]
**Describe the bug**
After bookmarking a session for Day 2 or 3, the state is lost and Day 1 is reselected.

**To Reproduce**
1. Go to "Sessions" 
2. Select "Day 2" or "Day 3"
3. Bookmark any session
4. "Day 1" is reselected

**Expected behavior**
Bookmarking a session doesn't trigger navigating to "Day 1" sessions

App Version: 1.0.6

**Comment by michaelbukachi** [comment]
Thanks @etonotieno. It will be resolved in #266

**Comment by kibettheophilus** [comment]
> Thanks @etonotieno. It will be resolved in #266

@michaelbukachi can we now close this?
