### ISSUE TITLE
Make feedback feature functional

### ISSUE THREAD

**Issue by daniel-waiguru** [droidconKE/droidconKeKotlin#274]
Is there an API endpoint for submitting feedback?

**Comment by chepsi** [comment]
Yes, there is. make a `post` request to 
```url  = {BaseUrl}/feedback``` with a body 
```dataClass(
@SerialName("feedback")
feedback: String,
@SerialName("rating")
rating: String
)```

**Comment by chepsi** [comment]
@daniel-waiguru can I assign this to you?

**Comment by daniel-waiguru** [comment]
Yes

**Comment by chepsi** [comment]
done. let me know if you need any help.

**Comment by daniel-waiguru** [comment]
@chepsi The route does not support POST methods, it only supports GET, which is currently returning internal server error

**Comment by chepsi** [comment]
Marking this as stale
