### ISSUE TITLE
Update Readme to include this year's events

### ISSUE THREAD

**Issue by chepsi** [droidconKE/droidconKeKotlin#276]
Currently, the `ReadMe` has information on last year's conference. We need to update the references to point to this year's events which will happen from the 6th to the 8th of November. This year will be the 5th conference.

**Comment by OkelloSam21** [comment]
@chepsi  can I work on this issue?

**Comment by chepsi** [comment]
Sure thing @OkelloSam21 . I will assign it to you.

**Comment by OkelloSam21** [comment]
> Sure thing @OkelloSam21 . I will assign it to you.

I've checked the current readme and it's up to date.

> ![image](https://github.com/droidconKE/droidconKeKotlin/assets/115361239/932f81a1-d106-412c-8b1c-66b9c5900a06)

If there's anything else that is missing out please let me know.

**Comment by chepsi** [comment]
Marking this as done
