### ISSUE TITLE
Remove fastlane and use github actions purely

### ISSUE THREAD

**Issue by kibettheophilus** [droidconKE/droidconKeKotlin#290]
All the open PRs are failing and the logs seems to be pointing to fastlane throwing an error. Proposing fastlane to be removed and only run workflows using github actions.

`N/B:` It is only the branch workflow using fastlane while deployment workflow is purely github actions.

**Comment by wangerekaharun** [comment]
@kibettheophilus the Fastlane issue should be fixed with the updating dependencies pr
