### ISSUE TITLE
Architecture Documentation for droidconKE 2023 app

### ISSUE THREAD

**Issue by tamzi** [droidconKE/droidconKeKotlin#3]
**Is your feature request related to a problem? Please describe.**
We need to have a proper architecture documentation that:
- Shows what the app will look like and features it plugs into.
- Lack of this documented vision and direction often causes confusion to the contributors.

**Describe the solution you'd like**
- Create documentation before we start implementing features. Tools like [Mockla](https://mockola.com/) or [draw.io ](https://app.diagrams.net/) and a link to the diagram made open then linked to a docs section in the app.
- Require documentation of features as they are developed(Inline + or - on the markdown.

**Describe alternatives you've considered**
No documentation is the alternative and its a painful experience.

**Additional context**
Previous calls for documentation have been ignored an explanation by code owners would be great. See [this issue](https://github.com/droidconKE/droidconKE2022Android/issues/75)

**Comment by jumaallan** [comment]
🤞

**Comment by chepsi** [comment]
Changing the title to droidcon 2023

**Comment by chepsi** [comment]
Marking this as stale
