### ISSUE TITLE
Show Loading States on Screens Fetching Data

### ISSUE THREAD

**Issue by wangerekaharun** [droidconKE/droidconKeKotlin#37]

**Comment by Mogakamo** [comment]
@wangerekaharun can I take this?

**Comment by wangerekaharun** [comment]
> @wangerekaharun can I take this?

Sure feel free it pick it up!

**Comment by Mogakamo** [comment]
ok. You can assign it to me.

**Comment by wangerekaharun** [comment]
> ok. You can assign it to me.

Done

**Comment by robert-nganga** [comment]
@wangerekaharun Can I work on this?

**Comment by wangerekaharun** [comment]
@robert-nganga  Yes you can pick it up since it's been some months and no updates from @mog-rn

**Comment by chepsi** [comment]
Marking this as stale
