### ISSUE TITLE
Filter Bottom Sheet To Match the Design

### ISSUE THREAD

**Issue by wangerekaharun** [droidconKE/droidconKeKotlin#95]

**Comment by MamboBryan** [comment]
| EXPECTED | ACTUAL |
|:------:|:------|
|<img width="335" alt="Screenshot 2023-04-05 at 1 56 15 AM" src="https://user-images.githubusercontent.com/40160345/229940032-81a5db78-a50d-4da3-ac3c-5b042ddee506.png">|<img width="348" alt="Screenshot 2023-04-05 at 2 01 31 AM" src="https://user-images.githubusercontent.com/40160345/229940749-7ec61c7e-606d-47c7-9db1-7b1686c98e38.png">|

**Comment by Joel-K-Muraguri** [comment]
Please assign this to me

**Comment by wangerekaharun** [comment]
@MamboBryan thoughts on this?

**Comment by josphatmwania** [comment]
@joelmuraguri Is there any progress?

**Comment by kibettheophilus** [comment]
@janewaitara was this fixed by #249 ?

**Comment by chepsi** [comment]
Marking this as stale
